# Generated by Django 2.2.28 on 2023-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_num', models.CharField(max_length=32, verbose_name='材料类别编号')),
                ('material_name', models.CharField(max_length=32, verbose_name='材料类别名称')),
                ('is_node_or_not', models.CharField(max_length=32, verbose_name='是否叶子节点')),
                ('father_num', models.CharField(max_length=32, verbose_name='所属父类编号')),
                ('material_class', models.CharField(max_length=32, verbose_name='所属材料库编号')),
                ('level', models.CharField(max_length=32, verbose_name='层级')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '材料库信息',
                'verbose_name_plural': '材料库信息',
                'db_table': 'material_information',
            },
        ),
    ]
