# Generated by Django 2.2.28 on 2023-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suanliang', '0002_auto_20230410_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise_quota_tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_num', models.CharField(max_length=32, verbose_name='定额类别编号')),
                ('quota_name', models.CharField(max_length=32, verbose_name='定额类别名称')),
                ('is_node_or_not', models.BooleanField(verbose_name='是否叶子节点')),
                ('father_num', models.CharField(max_length=32, verbose_name='所属父类编号')),
                ('quota_class', models.CharField(max_length=32, verbose_name='所属定额库编号')),
                ('level', models.CharField(max_length=32, verbose_name='层级')),
                ('engineering_class', models.CharField(max_length=32, verbose_name='所属施工工程类别')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '企业定额树信息',
                'verbose_name_plural': '企业定额树信息',
                'db_table': 'enterprise_quota_tree',
            },
        ),
        migrations.CreateModel(
            name='Job_detail_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail_num', models.CharField(max_length=32, verbose_name='工种编号')),
                ('job_detail_name', models.CharField(max_length=32, verbose_name='工种名称')),
                ('job_specification', models.CharField(max_length=32, verbose_name='工种规格')),
                ('job_unit', models.CharField(max_length=32, verbose_name='计量单位')),
                ('job_price', models.IntegerField(verbose_name='工种单价')),
                ('job_class_num', models.CharField(max_length=32, verbose_name='所属工种库类别编号')),
                ('job_class', models.CharField(max_length=32, verbose_name='所属工种库类型')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '工种明细信息',
                'verbose_name_plural': '工种明细信息',
                'db_table': 'job_detail_information',
            },
        ),
        migrations.CreateModel(
            name='Material_detail_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_detail_num', models.CharField(max_length=32, verbose_name='材料编号')),
                ('material_detail_name', models.CharField(max_length=32, verbose_name='材料名称')),
                ('material_specification', models.CharField(max_length=32, verbose_name='材料规格')),
                ('material_unit', models.CharField(max_length=32, verbose_name='材料单位')),
                ('material_price', models.IntegerField(verbose_name='材料单价')),
                ('material_class_num', models.CharField(max_length=32, verbose_name='所属材料库类别编号')),
                ('material_class', models.CharField(max_length=32, verbose_name='所属材料库类型')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '材料明细信息',
                'verbose_name_plural': '材料明细信息',
                'db_table': 'material_detail_information',
            },
        ),
        migrations.CreateModel(
            name='Quota_detail_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_detail_num', models.CharField(max_length=32, verbose_name='定额编号')),
                ('quota_detail_name', models.CharField(max_length=32, verbose_name='定额名称')),
                ('quota_unit', models.CharField(max_length=32, verbose_name='计量单位')),
                ('quota_price', models.IntegerField(verbose_name='定额单价')),
                ('quota_class_num', models.CharField(max_length=32, verbose_name='所属定额类别编号')),
                ('quota_class', models.CharField(max_length=32, verbose_name='所属定额类别')),
                ('engineering_class', models.CharField(max_length=32, verbose_name='所属施工工程类别')),
                ('quota_engineering', models.CharField(max_length=32, verbose_name='定额项目特征')),
                ('job_content', models.TextField(max_length=32, verbose_name='工作内容描述')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '工种明细信息',
                'verbose_name_plural': '工种明细信息',
                'db_table': 'quota_detail_information',
            },
        ),
        migrations.AlterField(
            model_name='job_information',
            name='job_class',
            field=models.CharField(max_length=32, verbose_name='所属工种库编号'),
        ),
        migrations.AlterField(
            model_name='material_information',
            name='material_class',
            field=models.CharField(max_length=32, verbose_name='所属材料库类型'),
        ),
    ]
