# Generated by Django 2.2.28 on 2023-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suanliang', '0003_auto_20230410_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_num', models.CharField(max_length=32, verbose_name='措施费率编号')),
                ('measure_name', models.CharField(max_length=32, verbose_name='措施费率名称')),
                ('measure_class', models.CharField(max_length=32, verbose_name='所属材料库类型')),
                ('measure_level', models.CharField(max_length=32, verbose_name='费率档次')),
                ('measure_subject', models.CharField(max_length=32, verbose_name='所属取费专业')),
                ('measure_rate', models.FloatField(verbose_name='对应费率')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '措施费率信息',
                'verbose_name_plural': '措施费率信息',
                'db_table': 'measure_rate_information',
            },
        ),
        migrations.CreateModel(
            name='Quota_business_detail_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_detail_num', models.CharField(max_length=32, verbose_name='定额编号')),
                ('quota_detail_name', models.CharField(max_length=32, verbose_name='定额名称')),
                ('relate_business_class', models.CharField(max_length=32, verbose_name='关联业务类别')),
                ('relate_business_num', models.CharField(max_length=32, verbose_name='关联业务编码')),
                ('relate_business_unit', models.CharField(max_length=32, verbose_name='关联业务单位')),
                ('relate_business_consume', models.FloatField(max_length=32, verbose_name='关联业务单位')),
                ('relate_business_fix_price', models.FloatField(max_length=32, verbose_name='关联业务定额价格')),
                ('relate_business_tax_price', models.FloatField(max_length=32, verbose_name='关联业务含税价')),
                ('coefficient', models.FloatField(default=1, max_length=32, verbose_name='系数')),
                ('original_consumption', models.FloatField(max_length=32, verbose_name='原始消耗量')),
                ('marks', models.FloatField(max_length=256, verbose_name='备注')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('create_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('update_name', models.CharField(max_length=32, verbose_name='创建人')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': '企业定额业务明细',
                'verbose_name_plural': '企业定额业务明细',
                'db_table': 'quota_business_detail_information',
            },
        ),
        migrations.AlterModelOptions(
            name='quota_detail_information',
            options={'verbose_name': '定额明细信息', 'verbose_name_plural': '定额明细信息'},
        ),
        migrations.AlterField(
            model_name='job_detail_information',
            name='job_price',
            field=models.FloatField(verbose_name='工种单价'),
        ),
        migrations.AlterField(
            model_name='material_detail_information',
            name='material_price',
            field=models.FloatField(verbose_name='材料单价'),
        ),
    ]
